stages:
  - build
  - release

variables:
  HTML_PATH: huishoudelijk-reglement.html

build:
  stage: build
  image: pandoc/latex:latest-alpine
  script:
    - mkdir dist
    - pandoc metadata.txt README.md -o dist/$HTML_PATH -s --toc --metadata title="Huishoudelijk Reglement"
  artifacts:
    paths:
      - dist/

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "running release_job for $CI_COMMIT_REF_NAME"
  release:                                         # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_REF_NAME'                # Keep one release per branch?
    description: '$CI_JOB_STARTED_AT'
    ref: '$CI_COMMIT_SHA'                          # The tag is created from the pipeline SHA.
    assets:
      links:
        - name: 'html'
          url: "${PACKAGE_REGISTRY_URL}/${HTML_PATH}"
