stages:
  - build
  - release

variables:
  HTML_PATH: huishoudelijk-reglement.html

build:
  stage: build
  image:
    name: pandoc/core
    entrypoint: ["/bin/sh", "-c"]
  script:
    # Writing GE_JOB_ID variable to environment file, will need the value in the next stage.
    - echo GE_JOB_ID=$CI_JOB_ID >> CI_JOB_ID.txt
    - mkdir dist
    - pandoc metadata.txt README.md -o dist/$HTML_PATH -s --toc --css=style.css --metadata title="Huishoudelijk Reglement"
  artifacts:
    paths:
      - dist/
    reports:
      # To ensure we've access to this file in the next stage
      dotenv: CI_JOB_ID.txt

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build
      artifacts: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run this job when commits are pushed or merged to the default branch
  script:
    - echo "running release_job for $CI_COMMIT_REF_NAME"
  release:                                         # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_REF_NAME'                # Keep one release per branch?
    description: '$CI_JOB_STARTED_AT'
    ref: '$CI_COMMIT_SHA'                          # The tag is created from the pipeline SHA.
    assets:
      links:
        - name: 'html'
          url: "https://gitlab.com/bij1/huishoudelijk-reglement/-/jobs/`cat CI_JOB_ID.txt`/artifacts/file/${HTML_PATH}"
