stages:
  - build
  - release

variables:
  HTML_PATH: huishoudelijk-reglement.html
  EPUB_PATH: huishoudelijk-reglement.epub
  PDF_PATH : huishoudelijk-reglement.pdf

build:
  stage: build
  image:
    name: pandoc/core
    entrypoint: ["/bin/sh", "-c"]
  script:
    - mkdir dist
    - pandoc metadata.txt README.md -o dist/$HTML_PATH -s --toc --css=style.css --metadata title="Huishoudelijk Reglement"
    - pandoc metadata.txt README.md -o dist/$EPUB_PATH -s --toc --css=style.css
  artifacts:
    paths:
      - dist/

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run this job when commits are pushed or merged to the default branch
  script:
    - echo "running release_job for $CI_COMMIT_REF_NAME"
  release:                                         # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_REF_NAME'                # Keep one release per branch?
    description: '$CI_JOB_STARTED_AT'
    ref: '$CI_COMMIT_SHA'                          # The tag is created from the pipeline SHA.
    assets:
      links:
        - name: 'html'
          url: "${PACKAGE_REGISTRY_URL}/${HTML_PATH}"
        - name: 'epub'
          url: "${PACKAGE_REGISTRY_URL}/${EPUB_PATH}"
        - name: 'pdf'
          url: "${PACKAGE_REGISTRY_URL}/${PDF_PATH}"
