pipeline:

  build-pandoc:
    image: pandoc/core:latest
    environment:
      - HTML_PATH=${CI_REPO_NAME}.html
      - EPUB_PATH=${CI_REPO_NAME}.epub
    commands:
      - apk update && apk add curl
      - mkdir dist
      - pandoc metadata.txt README.md -o dist/${HTML_PATH} -s --toc --css=style.css --self-contained --metadata title=$CI_PROJECT_NAME
      - pandoc metadata.txt README.md -o dist/${EPUB_PATH} -s --toc --css=style.css
      - curl --user ci:$TOKEN --upload-file dist/${HTML_PATH} https://code.bij1.org/api/packages/bij1/generic/${CI_REPO_NAME}/${CI_COMMIT_SOURCE_BRANCH}/${HTML_PATH}
      - curl --user ci:$TOKEN --upload-file dist/${EPUB_PATH} https://code.bij1.org/api/packages/bij1/generic/${CI_REPO_NAME}/${CI_COMMIT_SOURCE_BRANCH}/${EPUB_PATH}
    secrets: [ token ]
    when:
      - event: push
        branch: main

  build-pdf:
    image: pandoc/core:latest
    environment:
      - PDF_PATH=${CI_REPO_NAME}.pdf
    commands:
      - apk update && apk add curl
      - mkdir dist
      - xelatex --shell-escape -interaction=nonstopmode main.tex
      - cp main.pdf dist/${PDF_PATH}
      - curl --user ci:$TOKEN --upload-file dist/${HTML_PATH} https://code.bij1.org/api/packages/bij1/generic/${CI_REPO_NAME}/${CI_COMMIT_SOURCE_BRANCH}/${PDF_PATH}
    secrets: [ token ]
    when:
      - event: push
        branch: main
