pipeline:

  package:
    image: pandoc/latex:latest
    commands:
      - apk update && apk add curl
      - mkdir dist
      - pandoc metadata.txt README.md -o dist/${CI_REPO_NAME}.html -s --toc --css=style.css --self-contained --metadata title=$CI_PROJECT_NAME
      - curl --user ci:$TOKEN -X DELETE https://code.bij1.org/api/packages/bij1/generic/${CI_REPO_NAME}/html || true
      - curl --user ci:$TOKEN --upload-file dist/${CI_REPO_NAME}.html https://code.bij1.org/api/packages/bij1/generic/${CI_REPO_NAME}/html/${CI_REPO_NAME}.html
      - pandoc metadata.txt README.md -o dist/${CI_REPO_NAME}.epub -s --toc --css=style.css
      - curl --user ci:$TOKEN -X DELETE https://code.bij1.org/api/packages/bij1/generic/${CI_REPO_NAME}/epub || true
      - curl --user ci:$TOKEN --upload-file dist/${CI_REPO_NAME}.epub https://code.bij1.org/api/packages/bij1/generic/${CI_REPO_NAME}/epub/${CI_REPO_NAME}.epub
      - echo $PATH
      - which xelatex
      - xelatex --shell-escape -interaction=nonstopmode main.tex
      - curl --user ci:$TOKEN -X DELETE https://code.bij1.org/api/packages/bij1/generic/${CI_REPO_NAME}/pdf || true
      - curl --user ci:$TOKEN --upload-file main.pdf https://code.bij1.org/api/packages/bij1/generic/${CI_REPO_NAME}/pdf/${CI_REPO_NAME}.pdf
    secrets: [ token ]
    when:
      - event: push
        branch: main
